[tool.poetry]
name = "BadgeSort"
version = "3.1.5"
description = "Generate and sort branded Shields.io badges by color"
authors = ["Chip Wolf <github@chipwolf.uk>"]
license = "MIT"
readme = "README.md"
packages = [{include = "badgesort"}]

[tool.poetry.dependencies]
python = "^3.9"
certifi = "2025.10.5"
chardet = "5.2.0"
idna = "3.11"
poetry-core = "2.2.1"
requests = "2.32.5"
simpleicons = "7.21.0"
urllib3 = "2.5.0"
scour = "^0.38.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
